#!/usr/bin/env perl

# Copyright © 2022-2026 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

no lib '.';  # CVE-2016-1238

use autodie;
use strict;
use warnings;
use v5.14;

use English qw(-no_match_vars);
use FindBin ();
use HTTP::Tiny ();
use JSON::PP ();
use MIME::Base64 qw(decode_base64);

sub urlget
{
    my ($url) = @_;
    state $http = HTTP::Tiny->new;
    my $response = $http->get($url);
    if (not $response->{success}) {
        if ($response->{status} == 599) {
            die "<$url>: $response->{content}";
        } else {
            die "<$url>: $response->{status} $response->{reason}";
        }
    }
    return $response->{content};
}

chdir "$FindBin::Bin/..";

# https://github.com/zedeus/nitter/wiki/Instances
my $wiki_url = 'https://raw.githubusercontent.com/wiki/zedeus/nitter/Instances.md';
my $wiki = urlget($wiki_url);

$wiki =~ s/.*\n## Public\n//s;
$wiki =~ s/\n\K#.*//s;
my %hosts;
while ($wiki =~ m{^[|] \[([\w.]+)\][(]([\w:./]+)[)]}mg) {
    my $host = $1;
    my $url = $2;
    $url =~ m{\Ahttps://\Q$host\E/?\z}
        or die "Instances.md: bad line for host $host";
    if (defined $hosts{host}) {
        die "Instances.md: duplicate host $host"
    };
    $hosts{$host} = 1;
}

# https://codeberg.org/mv12star/shitter/wiki/Instances
my $api_url = 'https://codeberg.org/api/v1/repos/mv12star/shitter/wiki/page/Instances';
my $json = urlget($api_url);
$json = JSON::PP::decode_json($json);
$wiki = decode_base64($json->{content_base64});
my %hosts2;
while ($wiki =~ m{# (Working|Active).*\n(([^#].*\n)+)}g) {
    my $section = $2;
    while ($section =~ m{^- https://([\w.]+)}mg) {
        my $host = $1;
        if (defined $hosts2{host}) {
            die "shitter/Instances.md: duplicate host $host"
        };
        $hosts2{$host} = 1;
    }
}

for my $path (glob '*') {
    my $target = eval { readlink $path }
        or next;
    $target eq 'nitter.net'
        or next;
    unlink $path;
}

%hosts = (%hosts, %hosts2);
for my $host (keys %hosts) {
    symlink 'nitter.net', $host;
}

# vim:ts=4 sts=4 sw=4 et
